### ISSUE TITLE
action.yml error

### ISSUE THREAD

**Issue by BL-marcusrogers** [PoisonousJohn/upload-to-kobiton#12]
Getting an error when trying to use the action. Error is:

`Error: PoisonousJohn/upload-to-kobiton/v1/action.yml (Line: 14, Col: 14): Unexpected value 'Id of an uploaded version'`

Looks like the format for outputs in the action.yml file should be:

`outputs:`
`versionId:`
`description: "Id of an uploaded version"`

**Comment by PoisonousJohn** [comment]
@BL-marcusrogers I've released v1.1, I have no opportunity to test it, since I'm not using kobiton anymore. Could you please check it?

**Comment by BL-marcusrogers** [comment]
Thanks, that worked.

Looks like the action is built for .apk files only (the file name is hard coded with the .apk extension: https://github.com/PoisonousJohn/upload-to-kobiton/blob/6d3d71eb6b2eb7556af78db6c03262a7485d2cf2/src/main.ts#L13). I created a PR to add the file name as an input and use that to allow .aab, .ipa, etc. (https://github.com/PoisonousJohn/upload-to-kobiton/pull/13).

**Comment by BL-marcusrogers** [comment]
@PoisonousJohn If you have a minute could you take a look at the above PR?

**Comment by BL-marcusrogers** [comment]
@PoisonousJohn no problem, thanks for creating the action! Unfortunately I missed one more spot where the filename needs to be specified to get the correct extension for Kobiton. One more PR if you have the time: https://github.com/PoisonousJohn/upload-to-kobiton/pull/14.

**Comment by PoisonousJohn** [comment]
@BL-marcusrogers thanks, published as v1.3
